let ValidationError,CustomErrorHandler;_59c‍.x([["default",()=>_59c‍.o]]);_59c‍.w("joi",[["ValidationError",["ValidationError"],function(v){ValidationError=v}]]);_59c‍.w("../service/customErrorHandler",[["default",["CustomErrorHandler"],function(v){CustomErrorHandler=v}]]);
// error handling code for application 




const errorHandler=(err,req,res,next)=>{

    let status=500;

    let data={
        message:'internal sever error',
        originalerr:err
    }

    console.log("error in the application");
    
    _59c‍.g.console.log(data.originalerr);
    
   
    if(err instanceof ValidationError){

        status=403;
        data.message=err.message;

return res.status(status).json({status,message:data.message});
        
    }

    if(err instanceof CustomErrorHandler){

        status=err.status;
        data.message=err.message;


        return res.status(status).json({status,message:data.message});
    }



    return res.status(status).json({status,message:data.message});
    



}


_59c‍.d(errorHandler);


